---
title: "Data science project - Suicidial attacks"
author: "Mr. Jakob Alderson & MR. Tal Bracha"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r, echo= FALSE, message=FALSE}
library(tidyverse)
library(mapview)
library(sf)
library(ggplot2)
library(ggmap)
library(tseries)
library(car)
library(moments)
library(writexl)
library(AID)
```


## inro

why its impotent

## litetature 

##hypothesis

## Suicidal attacks global or middle eastern problem?

```{r}
points = read.csv("attacks.csv")
points = points[!is.na(points$latitude), ]
points = points[!is.na(points$longitude), ]
```

```{r, warning=FALSE}

world <- map_data("world")
   ggplot() +
     geom_map(
       data = world, map = world,
       aes(long, lat, map_id = region),
       color = "black", fill = "lightgray", size = 0.1
     ) +
     geom_point(
       data = points,
       aes(longitude, latitude), color = "blue",
       alpha = 0.7
     ) 
```

Point density:
```{r}
ggplot(points, aes(x = longitude, y = latitude)) + 
     geom_point() + 
     coord_equal() + 
     xlab('longitude') + 
     ylab('latitude') + 
     stat_density2d(aes(fill = ..level..), alpha = 100,
                    geom = "polygon", data = points) + 
     scale_fill_viridis_c() + 
     theme(legend.position = 'none') 
```

The middle east  is the brightest

## Data Cleaning and Normaliry

Before cleanig:

```{r}
attacks = read.csv("attacks.csv")
head(as_tibble(attacks))
```
 
After some data organization:
```{r}
attacks = as_tibble(attacks) %>%
  select(event_id,wounded_low,wounded_high,killed_low,killed_high) %>%
  filter(wounded_low >= 0) %>%
  filter(wounded_high >= 0) %>%
  filter(killed_low >= 0) %>%
  filter(killed_high >= 0) %>%
  mutate(wounded_average = round(((wounded_low + wounded_high)/2) )) %>%
  mutate(killed_average = round(((killed_low + killed_high)/2) )) %>% 
  mutate(casualties = wounded_average + killed_average) %>%
  filter(casualties >= 1) %>%
  select(event_id,wounded_average,killed_average,casualties)
 head(attacks)
```


